site:
  title: POC Documentation Antora
  start_page: component-a::index.adoc
content:
  sources:
  - url: https://github.com/jay-blanc/antora-doc-asciidoc.git
    branches: master
  - url: https://github.com/jay-blanc/antora-doc-asciidoc-plantuml-simple.git
    branches: master
  - url: https://github.com/jay-blanc/antora-doc-asciidoc-plantuml-iuml.git
    branches: master
ui:
  bundle:
    url: ./ui-bundle.zip
asciidoc:
  attributes:
    kroki-server-url: http://<SET_HERE_YOUR_KROKI_SERVER>:8000
    kroki-fetch-diagram: true
    kroki-http-method: post
    source-highlighter: highlight.js
    icons: font
    icon-set: fa
  extensions:
  - ./asciidoctor-kroki/src/asciidoctor-kroki.js
